name: Joomla Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        lando-version:
          - 3-edge
        os:
          - ubuntu-24.04
        node-version:
          - '20'
        leia-test:
          - examples/joomla-custom
          - examples/joomla-defaults
          - examples/joomla-downstreamer-1
          - examples/joomla-downstreamer-2
          - examples/joomla-export
          - examples/joomla-import
          - examples/joomla-init
          - examples/joomla-mariadb
          - examples/joomla-mariadb-mysql
          - examples/joomla-mysql8
          - examples/joomla-nginx

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install NPM dependencies
        run: npm clean-install --production --prefer-offline --frozen-lockfile
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/joomla=/home/runner/work/joomla/joomla
          telemetry: false
      - name: Run Leia Tests
        uses: lando/run-leia-action@v2
        with:
          leia-test: "./${{ matrix.leia-test }}/README.md"
          cleanup-header: "Destroy tests"
          shell: bash
          stdin: true
